// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    [Migration("20181018152220_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WebApi.Model.Exercise", b =>
                {
                    b.Property<int>("exerciseId")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("answer");

                    b.Property<bool>("correctAnswerGiven");

                    b.Property<int>("leftNumber");

                    b.Property<int>("mathOperator");

                    b.Property<int>("rightNumber");

                    b.Property<Guid>("userId");

                    b.HasKey("exerciseId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("WebApi.Model.Score", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("highScore");

                    b.Property<int>("level");

                    b.HasKey("userId");

                    b.ToTable("Score");
                });
#pragma warning restore 612, 618
        }
    }
}
